mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('display/', views.DisplayView.as_view(), name='display'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('product/', views.ProductView.as_view(), name='product_index'),
    path('product/buy/<int:product_id>', views.buy, name='buy_product'),
    path('<int:pk>/result/', views.CompletedView.as_view(), name='product_result'),
    path('get/', views.get_reply, name='get'),

]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator


# Create your models here.

class Question(models.Model):
    
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):

    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Product(models.Model):
    
    upccode = models.CharField('UPC code',max_length=14)
    description = models.CharField('Description', max_length=60)
    price = models.DecimalField("Unit Price", 
            max_digits=9, decimal_places=2)
    quantity = models.IntegerField("Quantity", validators=[MinValueValidator(0)])

    

    def __str__(self):
        return (f"{self.description} {self.price}฿ remained:{self.quantity}")

def quantity_in_stock(self,text):
        """Compute and return number of units in stock"""
        p = Product.objects.filter(text__contain = text)

        return [p]

polls/forms.py
from django import forms

class NameForm(forms.Form):
    name = forms.CharField(max_length=100, required=True)

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question, Product

class IndexView(generic.ListView):
    model = Question
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


class DisplayView(generic.ListView):
    model = Question
    template_name = 'polls/display.html'
    context_object_name = 'latest_question_list'


class ProductView(generic.ListView):
    model = Product
    template_name = 'polls/product_index.html'
    context_object_name = 'latest_product_list'

class CompletedView(generic.DetailView):
    model = Product
    template_name = 'polls/product_result.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Product.objects.filter()


def buy(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.quantity -= 1
    product.save()
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('polls:product_result', args=(product.id,)))

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def get_reply( prompt_msg ):
      reply = input( prompt_msg )
      return reply.lower( )
 
# use the method
reply = get_reply( "Do you like Python? " )
if reply == "yes":
    print("Good! So do I.")
else:
    print('Sorry. Try Javascript instead.')

polls/templates/polls/detail.html
<body style="background:url('https://i.redd.it/ck8lswwqnwl11.png') no-repeat";>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
</body>

polls/templates/polls/display.html
<body style="background:url('https://i.redd.it/ck8lswwqnwl11.png') no-repeat";>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li>
        <p>{{ question.question_text }}</p>
        <ul>
            {% for choice in question.choice_set.all %}
            <li>
                <p>{{ choice }}: {{ choice.votes }}</p>
            </li>
            {% endfor %}
        </ul>
    </li> 
    {% endfor %}
    </ul>
      <a href="{% url 'polls:index' %}">Home</a>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>

polls/templates/polls/index.html
<body style="background:url('https://i.redd.it/ck8lswwqnwl11.png') no-repeat";>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li>
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
    </li>    
    {% endfor %}
    </ul>
      <a href="{% url 'polls:display' %}">View all choice</a>
      <br>
      <a href="{% url 'polls:product_index' %}">View Product</a>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>

polls/templates/polls/product_index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<body style="background:url('https://i.redd.it/ck8lswwqnwl11.png') no-repeat";>
    {% if latest_product_list %}
        <table>
            <tr>
                <th>UPC Code</th>
                <th>Description</th>   
                <th>Qnty in Stock<s/th>   
                <th>Unit Price</th> 
            </tr>
            {% for product in latest_product_list %}
            <tr>
                <td>{{ product.upccode }}</td>
                <td >{{ product.description }}</td>
                <td >{{ product.quantity_in_stock }}</td>
                <td >{{ product.price }}</td>
            </tr>
            {% endfor %}
        </table>
        <h1>Product</h1>
        {% for product in latest_product_list %}
            <ul>
            <li>
                <form action="{% url 'polls:buy_product' product.id %}" method="post">
                    {% csrf_token %}
                        <label for="product{{ forloop.counter }}">{{ product.description }} {{ product.price }}฿ {{ product.quantity }}</label><br>
                        <input type="radio" name="product" id="product{{ forloop.counter }}" value="{{ product.id }}">
            </li>    
            </ul>
        {% endfor %}
        <input type="submit" value="buy">
    {% else %}
        <p>No product are created.</p>
    {% endif %}
    &nbsp;&nbsp;
    <a href="{% url 'polls:index' %}">Home</a>

</body>

polls/templates/polls/product_result.html
<body style="background:url('https://i.redd.it/ck8lswwqnwl11.png') no-repeat";>
    <h1>Product</h1>
    
    <ul>
    {% for product in product.objects.all %}
        <li>{{ product.description }} -- {{ product.price }} qnty in stock{{ product.quantity }}</li>
    {% endfor %}
    </ul>
    
    <a href="{% url 'polls:index' %}">Home</a>
    &nbsp;&nbsp;
    <a href="{% url 'polls:product_index' %}">View product</a>
    </body>

polls/templates/polls/results.html
<body style="background:url('https://i.redd.it/ck8lswwqnwl11.png') no-repeat";>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:index' %}">Home</a>
&nbsp;&nbsp;
<a href="{% url 'polls:display' %}">View votes</a>
</body>